common: &common
  adapter: postgresql
  username: kixo
  password: eb4q801T

development:
  <<: *common
  database: kixo_development

test:
  <<: *common
  database: kixo_test

production:
  <<: *common
  database: kixo_production
