# encoding: UTF-8

# locales
Locale.destroy_all
locale_en = Locale.create(:name => "English", :code => "en")
locale_fr = Locale.create(:name => "Français", :code => "fr")

# ratings
Rating.destroy_all
  RatingName.destroy_all

rating = Rating.create()
  rating_name = RatingName.create(:name => "Excellent", :locale => locale_en, :rating => rating)
  rating_name = RatingName.create(:name => "Excellent", :locale => locale_fr, :rating => rating)

rating = Rating.create()
  rating_name = RatingName.create(:name => "Good", :locale => locale_en, :rating => rating)
  rating_name = RatingName.create(:name => "Bien", :locale => locale_fr, :rating => rating)

rating = Rating.create()
  rating_name = RatingName.create(:name => "Average", :locale => locale_en, :rating => rating)
  rating_name = RatingName.create(:name => "Moyen", :locale => locale_fr, :rating => rating)

rating = Rating.create()
  rating_name = RatingName.create(:name => "Poor", :locale => locale_en, :rating => rating)
  rating_name = RatingName.create(:name => "Médiocre", :locale => locale_fr, :rating => rating)

rating = Rating.create()
  rating_name = RatingName.create(:name => "Disappointing", :locale => locale_en, :rating => rating)
  rating_name = RatingName.create(:name => "Décevant", :locale => locale_fr, :rating => rating)

# question statuses
QuestionStatus.destroy_all
  QuestionStatusName.destroy_all

question_status = QuestionStatus.create()
  question_status_name = QuestionStatusName.create(:name => "Open", :locale => locale_en, :question_status => question_status)
  question_status_name = QuestionStatusName.create(:name => "Ouverte", :locale => locale_fr, :question_status => question_status)

question_status = QuestionStatus.create()
  question_status_name = QuestionStatusName.create(:name => "Answered", :locale => locale_en, :question_status => question_status)
  question_status_name = QuestionStatusName.create(:name => "Répondue", :locale => locale_fr, :question_status => question_status)

question_status = QuestionStatus.create()
  question_status_name = QuestionStatusName.create(:name => "Closed", :locale => locale_en, :question_status => question_status)
  question_status_name = QuestionStatusName.create(:name => "Fermée", :locale => locale_fr, :question_status => question_status)

question_status = QuestionStatus.create()
  question_status_name = QuestionStatusName.create(:name => "Denied", :locale => locale_en, :question_status => question_status)
  question_status_name = QuestionStatusName.create(:name => "Refusée", :locale => locale_fr, :question_status => question_status)

# question visibilities
QuestionVisibility.destroy_all
  QuestionVisibilityName.destroy_all

question_visibility = QuestionVisibility.create()
  question_visibility_name = QuestionVisibilityName.create(:name => "Public", :locale => locale_en, :question_visibility => question_visibility)
  question_visibility_name = QuestionVisibilityName.create(:name => "Publique", :locale => locale_fr, :question_visibility => question_visibility)

question_visibility = QuestionVisibility.create()
  question_visibility_name = QuestionVisibilityName.create(:name => "Private", :locale => locale_en, :question_visibility => question_visibility)
  question_visibility_name = QuestionVisibilityName.create(:name => "Privée", :locale => locale_fr, :question_visibility => question_visibility)

# guide statuses
GuideStatus.destroy_all
  GuideStatusName.destroy_all

guide_status = GuideStatus.create()
  guide_status_name = GuideStatusName.create(:name => "Published", :locale => locale_en, :guide_status => guide_status)
  guide_status_name = GuideStatusName.create(:name => "Publié", :locale => locale_fr, :guide_status => guide_status)

guide_status = GuideStatus.create()
  guide_status_name = GuideStatusName.create(:name => "Draft", :locale => locale_en, :guide_status => guide_status)
  guide_status_name = GuideStatusName.create(:name => "Brouillon", :locale => locale_fr, :guide_status => guide_status)

# categories, topics, and professions
Category.destroy_all
  CategoryName.destroy_all
  CategoryDescription.destroy_all

  Topic.destroy_all
    TopicName.destroy_all
    TopicDescription.destroy_all

  Profession.destroy_all
    ProfessionName.destroy_all
    ProfessionDescription.destroy_all

category = Category.create()
  category_name = CategoryName.create(:name => "Legal", :locale => locale_en, :category => category)
  category_name = CategoryName.create(:name => "Juridique", :locale => locale_fr, :category => category)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Business", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "Corporatif", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Car Accidents", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "Accidents automobiles", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Child Custody", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Child Support", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Criminal Defense", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Divorce", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "DUI", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Employment", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Family", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Foreclosure", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Immigration", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Mariage", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Personal Injury", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Real Estate", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Attorney", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Lawyer", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

category = Category.create()
  category_name = CategoryName.create(:name => "Health", :locale => locale_en, :category => category)
  category_name = CategoryName.create(:name => "Santé", :locale => locale_fr, :category => category)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Acne", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Angina", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Asthma", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Botox", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Breast Augmentations", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Cataract", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Cervical Cancer", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Face Lift", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "HPV", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Invisalign", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "LASIK", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Liposuction", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Melanoma", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Pregnancy", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Rhinoplasty", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Root Canal", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Teeth Whitening", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Tummy Tuck", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Doctor", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

category = Category.create()
  category_name = CategoryName.create(:name => "Finance", :locale => locale_en, :category => category)
  category_name = CategoryName.create(:name => "Finances", :locale => locale_fr, :category => category)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Accounting", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Bankruptcy", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Bookkeeping", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Credit", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Estates", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Franchise", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Investment", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Mortgage", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Mutual Funds", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Payroll", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Personal Finance", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Stocks", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  topic = Topic.create(:category => category)
    topic_name = TopicName.create(:name => "Taxes", :locale => locale_en, :topic => topic)
    topic_name = TopicName.create(:name => "", :locale => locale_fr, :topic => topic)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Accountant", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Bankruptcy Trustee", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Investment Broker", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

  profession = Profession.create(:category => category)
    profession_name = ProfessionName.create(:name => "Real Estate Broker", :locale => locale_en, :profession => profession)
    profession_name = ProfessionName.create(:name => "", :locale => locale_fr, :profession => profession)

# countries, regions, and localities
Country.destroy_all
  Region.destroy_all
    Locality.destroy_all

country = Country.create(:name => "Canada")

  region = Region.create(:name => "Ontario", :country_id => country.id)

    locality = Locality.create(:name => "Barrie", :population => 128430, :region => region)
    locality = Locality.create(:name => "Belleville", :population => 48821, :region => region)
    locality = Locality.create(:name => "Brampton", :population => 433806, :region => region)
    locality = Locality.create(:name => "Brant", :population => 34415, :region => region)
    locality = Locality.create(:name => "Brantford", :population => 90192, :region => region)
    locality = Locality.create(:name => "Brockville", :population => 21957, :region => region)
    locality = Locality.create(:name => "Burlington", :population => 164415, :region => region)
    locality = Locality.create(:name => "Cambridge", :population => 120371, :region => region)
    locality = Locality.create(:name => "Chatham-Kent", :population => 108177, :region => region)
    locality = Locality.create(:name => "Clarence-Rockland", :population => 20790, :region => region)
    locality = Locality.create(:name => "Cornwall", :population => 45965, :region => region)
    locality = Locality.create(:name => "Dryden", :population => 8195, :region => region)
    locality = Locality.create(:name => "Elliot Lake", :population => 11549, :region => region)
    locality = Locality.create(:name => "Greater Sudbury", :population => 157857, :region => region)
    locality = Locality.create(:name => "Guelph", :population => 114943, :region => region)
    locality = Locality.create(:name => "Haldimand County", :population => 45212, :region => region)
    locality = Locality.create(:name => "Hamilton", :population => 504559, :region => region)
    locality = Locality.create(:name => "Kawartha Lakes", :population => 74561, :region => region)
    locality = Locality.create(:name => "Kenora", :population => 15177, :region => region)
    locality = Locality.create(:name => "Kingston", :population => 117207, :region => region)
    locality = Locality.create(:name => "Kitchener", :population => 204668, :region => region)
    locality = Locality.create(:name => "London", :population => 352395, :region => region)
    locality = Locality.create(:name => "Markham", :population => 261573, :region => region)
    locality = Locality.create(:name => "Mississauga", :population => 668549, :region => region)
    locality = Locality.create(:name => "Niagara Falls", :population => 82184, :region => region)
    locality = Locality.create(:name => "Norfolk County", :population => 60847, :region => region)
    locality = Locality.create(:name => "North Bay", :population => 53966, :region => region)
    locality = Locality.create(:name => "Orillia", :population => 30259, :region => region)
    locality = Locality.create(:name => "Oshawa", :population => 141590, :region => region)
    locality = Locality.create(:name => "Ottawa", :population => 812129, :region => region)
    locality = Locality.create(:name => "Owen Sound", :population => 21753, :region => region)
    locality = Locality.create(:name => "Pembroke", :population => 13930, :region => region)
    locality = Locality.create(:name => "Peterborough", :population => 74898, :region => region)
    locality = Locality.create(:name => "Pickering", :population => 87838, :region => region)
    locality = Locality.create(:name => "Prince Edward County", :population => 25496, :region => region)
    locality = Locality.create(:name => "Port Colborne", :population => 18599, :region => region)
    locality = Locality.create(:name => "Quinte West", :population => 42697, :region => region)
    locality = Locality.create(:name => "Sarnia", :population => 71419, :region => region)
    locality = Locality.create(:name => "Sault Ste. Marie", :population => 74948, :region => region)
    locality = Locality.create(:name => "St. Catharines", :population => 131989, :region => region)
    locality = Locality.create(:name => "St. Thomas", :population => 36110, :region => region)
    locality = Locality.create(:name => "Stratford", :population => 30461, :region => region)
    locality = Locality.create(:name => "Temiskaming Shores", :population => 10442, :region => region)
    locality = Locality.create(:name => "Thorold", :population => 18224, :region => region)
    locality = Locality.create(:name => "Thunder Bay", :population => 109140, :region => region)
    locality = Locality.create(:name => "Timmins", :population => 42997, :region => region)
    locality = Locality.create(:name => "Toronto", :population => 2503281, :region => region)
    locality = Locality.create(:name => "Vaughan", :population => 238866, :region => region)
    locality = Locality.create(:name => "Waterloo", :population => 97475, :region => region)
    locality = Locality.create(:name => "Welland", :population => 50331, :region => region)
    locality = Locality.create(:name => "Windsor", :population => 216473, :region => region)
    locality = Locality.create(:name => "Woodstock", :population => 35480, :region => region)

  region = Region.create(:name => "Québec", :country_id => country.id)

    locality = Locality.create(:name => "Acton Vale", :population => 7797, :region => region)
    locality = Locality.create(:name => "Alma", :population => 29998, :region => region)
    locality = Locality.create(:name => "Amos", :population => 12584, :region => region)
    locality = Locality.create(:name => "Amqui", :population => 6261, :region => region)
    locality = Locality.create(:name => "Asbestos", :population => 6819, :region => region)
    locality = Locality.create(:name => "Baie-Comeau", :population => 22554, :region => region)
    locality = Locality.create(:name => "Baie-d'Urfé", :population => 3902, :region => region)
    locality = Locality.create(:name => "Baie-Saint-Paul", :population => 7288, :region => region)
    locality = Locality.create(:name => "Barkmere", :population => 87, :region => region)
    locality = Locality.create(:name => "Beaconsfield", :population => 19194, :region => region)
    locality = Locality.create(:name => "Beauceville", :population => 6226, :region => region)
    locality = Locality.create(:name => "Beauharnois", :population => 11918, :region => region)
    locality = Locality.create(:name => "Beaupré", :population => 3006, :region => region)
    locality = Locality.create(:name => "Bécancour", :population => 11134, :region => region)
    locality = Locality.create(:name => "Bedford", :population => 2612, :region => region)
    locality = Locality.create(:name => "Belleterre", :population => 350, :region => region)
    locality = Locality.create(:name => "Beloeil", :population => 18927, :region => region)
    locality = Locality.create(:name => "Berthierville", :population => 4007, :region => region)
    locality = Locality.create(:name => "Blainville", :population => 46493, :region => region)
    locality = Locality.create(:name => "Bois-des-Filion", :population => 8383, :region => region)
    locality = Locality.create(:name => "Boisbriand", :population => 26483, :region => region)
    locality = Locality.create(:name => "Bonaventure", :population => 2673, :region => region)
    locality = Locality.create(:name => "Boucherville", :population => 39062, :region => region)
    locality = Locality.create(:name => "Lac-Brome", :population => 5629, :region => region)
    locality = Locality.create(:name => "Bromont", :population => 6049, :region => region)
    locality = Locality.create(:name => "Brossard", :population => 71154, :region => region)
    locality = Locality.create(:name => "Brownsburg-Chatham", :population => 6664, :region => region)
    locality = Locality.create(:name => "Candiac", :population => 15947, :region => region)
    locality = Locality.create(:name => "Cap-Chat", :population => 2777, :region => region)
    locality = Locality.create(:name => "Cap-Santé", :population => 2666, :region => region)
    locality = Locality.create(:name => "Carignan", :population => 7426, :region => region)
    locality = Locality.create(:name => "Carleton-sur-Mer", :population => 4077, :region => region)
    locality = Locality.create(:name => "Causapscal", :population => 2556, :region => region)
    locality = Locality.create(:name => "Chambly", :population => 22608, :region => region)
    locality = Locality.create(:name => "Chandler", :population => 7914, :region => region)
    locality = Locality.create(:name => "Chapais", :population => 1630, :region => region)
    locality = Locality.create(:name => "Charlemagne", :population => 5594, :region => region)
    locality = Locality.create(:name => "Châteauguay", :population => 42786, :region => region)
    locality = Locality.create(:name => "Château-Richer", :population => 3563, :region => region)
    locality = Locality.create(:name => "Chibougamau", :population => 7563, :region => region)
    locality = Locality.create(:name => "Clermont", :population => 3041, :region => region)
    locality = Locality.create(:name => "Coaticook", :population => 9204, :region => region)
    locality = Locality.create(:name => "Contrecoeur", :population => 5678, :region => region)
    locality = Locality.create(:name => "Cookshire-Eaton", :population => 5004, :region => region)
    locality = Locality.create(:name => "Côte-Saint-Luc", :population => 31395, :region => region)
    locality = Locality.create(:name => "Coteau-du-Lac", :population => 6842, :region => region)
    locality = Locality.create(:name => "Cowansville", :population => 12182, :region => region)
    locality = Locality.create(:name => "Danville", :population => 4041, :region => region)
    locality = Locality.create(:name => "Daveluyville", :population => 1005, :region => region)
    locality = Locality.create(:name => "Dégelis", :population => 3209, :region => region)
    locality = Locality.create(:name => "Delson", :population => 7322, :region => region)
    locality = Locality.create(:name => "Desbiens", :population => 1074, :region => region)
    locality = Locality.create(:name => "Deux-Montagnes", :population => 17402, :region => region)
    locality = Locality.create(:name => "Disraeli", :population => 2570, :region => region)
    locality = Locality.create(:name => "Dolbeau-Mistassini", :population => 14546, :region => region)
    locality = Locality.create(:name => "Dollard-des-Ormeaux", :population => 48930, :region => region)
    locality = Locality.create(:name => "Donnacona", :population => 5564, :region => region)
    locality = Locality.create(:name => "Dorval", :population => 18088, :region => region)
    locality = Locality.create(:name => "Drummondville", :population => 67392, :region => region)
    locality = Locality.create(:name => "Dunham", :population => 3396, :region => region)
    locality = Locality.create(:name => "Duparquet", :population => 650, :region => region)
    locality = Locality.create(:name => "East Angus", :population => 3357, :region => region)
    locality = Locality.create(:name => "Estérel", :population => 256, :region => region)
    locality = Locality.create(:name => "Farnham", :population => 7809, :region => region)
    locality = Locality.create(:name => "Fermont", :population => 2633, :region => region)
    locality = Locality.create(:name => "Forestville", :population => 3543, :region => region)
    locality = Locality.create(:name => "Fossambault-sur-le-Lac", :population => 1532, :region => region)
    locality = Locality.create(:name => "Gaspé", :population => 14819, :region => region)
    locality = Locality.create(:name => "Gatineau", :population => 242124, :region => region)
    locality = Locality.create(:name => "Gracefield", :population => 2439, :region => region)
    locality = Locality.create(:name => "Granby", :population => 47637, :region => region)
    locality = Locality.create(:name => "Grande-Rivière", :population => 3409, :region => region)
    locality = Locality.create(:name => "Hampstead", :population => 6996, :region => region)
    locality = Locality.create(:name => "Hudson", :population => 5088, :region => region)
    locality = Locality.create(:name => "Huntingdon", :population => 2587, :region => region)
    locality = Locality.create(:name => "Joliette", :population => 19045, :region => region)
    locality = Locality.create(:name => "Kingsey Falls", :population => 2086, :region => region)
    locality = Locality.create(:name => "Kirkland", :population => 20491, :region => region)
    locality = Locality.create(:name => "L'Ancienne-Lorette", :population => 16516, :region => region)
    locality = Locality.create(:name => "L'Assomption", :population => 16738, :region => region)
    locality = Locality.create(:name => "L'Épiphanie", :population => 4606, :region => region)
    locality = Locality.create(:name => "L'Île-Cadieux", :population => 128, :region => region)
    locality = Locality.create(:name => "L'Île-Dorval", :population => 59, :region => region)
    locality = Locality.create(:name => "L'Île-Perrot", :population => 9927, :region => region)
    locality = Locality.create(:name => "La Malbaie", :population => 8959, :region => region)
    locality = Locality.create(:name => "La Pocatière", :population => 4575, :region => region)
    locality = Locality.create(:name => "La Prairie", :population => 21763, :region => region)
    locality = Locality.create(:name => "La Sarre", :population => 7336, :region => region)
    locality = Locality.create(:name => "La Tuque", :population => 11821, :region => region)
    locality = Locality.create(:name => "Lac-Delage", :population => 530, :region => region)
    locality = Locality.create(:name => "Lac-Mégantic", :population => 5967, :region => region)
    locality = Locality.create(:name => "Lac-Saint-Joseph", :population => 266, :region => region)
    locality = Locality.create(:name => "Lac-Sergent", :population => 423, :region => region)
    locality = Locality.create(:name => "Lachute", :population => 11832, :region => region)
    locality = Locality.create(:name => "Laval", :population => 376845, :region => region)
    locality = Locality.create(:name => "Lavaltrie", :population => 12112, :region => region)
    locality = Locality.create(:name => "Lebel-sur-Quévillon", :population => 2729, :region => region)
    locality = Locality.create(:name => "Léry", :population => 2385, :region => region)
    locality = Locality.create(:name => "Lévis", :population => 130006, :region => region)
    locality = Locality.create(:name => "Longueuil", :population => 229330, :region => region)
    locality = Locality.create(:name => "Lorraine", :population => 9613, :region => region)
    locality = Locality.create(:name => "Louiseville", :population => 7433, :region => region)
    locality = Locality.create(:name => "Macamic", :population => 2726, :region => region)
    locality = Locality.create(:name => "Magog", :population => 23880, :region => region)
    locality = Locality.create(:name => "Malartic", :population => 3640, :region => region)
    locality = Locality.create(:name => "Maniwaki", :population => 4102, :region => region)
    locality = Locality.create(:name => "Marieville", :population => 7904, :region => region)
    locality = Locality.create(:name => "Mascouche", :population => 34626, :region => region)
    locality = Locality.create(:name => "Matagami", :population => 1555, :region => region)
    locality = Locality.create(:name => "Matane", :population => 14742, :region => region)
    locality = Locality.create(:name => "Mercier", :population => 10121, :region => region)
    locality = Locality.create(:name => "Métabetchouan–Lac-à-la-Croix", :population => 4084, :region => region)
    locality = Locality.create(:name => "Métis-sur-Mer", :population => 604, :region => region)
    locality = Locality.create(:name => "Mirabel", :population => 34626, :region => region)
    locality = Locality.create(:name => "Mont-Joli", :population => 6568, :region => region)
    locality = Locality.create(:name => "Mont-Laurier", :population => 13405, :region => region)
    locality = Locality.create(:name => "Mont-Saint-Hilaire", :population => 15720, :region => region)
    locality = Locality.create(:name => "Mont-Tremblant", :population => 8892, :region => region)
    locality = Locality.create(:name => "Montmagny", :population => 11724, :region => region)
    locality = Locality.create(:name => "Montreal", :population => 1620693, :region => region)
    locality = Locality.create(:name => "Montréal-Est", :population => 3822, :region => region)
    locality = Locality.create(:name => "Montréal-Ouest", :population => 5184, :region => region)
    locality = Locality.create(:name => "Mont-Royal", :population => 18933, :region => region)
    locality = Locality.create(:name => "Murdochville", :population => 812, :region => region)
    locality = Locality.create(:name => "Neuville", :population => 3638, :region => region)
    locality = Locality.create(:name => "New Richmond", :population => 3748, :region => region)
    locality = Locality.create(:name => "Nicolet", :population => 7827, :region => region)
    locality = Locality.create(:name => "Normandin", :population => 3220, :region => region)
    locality = Locality.create(:name => "Notre-Dame-de-l'Île-Perrot", :population => 9885, :region => region)
    locality = Locality.create(:name => "Notre-Dame-des-Prairies", :population => 8230, :region => region)
    locality = Locality.create(:name => "Otterburn Park", :population => 8464, :region => region)
    locality = Locality.create(:name => "Paspébiac", :population => 3159, :region => region)
    locality = Locality.create(:name => "Percé", :population => 3419, :region => region)
    locality = Locality.create(:name => "Pincourt", :population => 11197, :region => region)
    locality = Locality.create(:name => "Plessisville", :population => 6677, :region => region)
    locality = Locality.create(:name => "Pohénégamook", :population => 2940, :region => region)
    locality = Locality.create(:name => "Pointe-Claire", :population => 30161, :region => region)
    locality = Locality.create(:name => "Pont-Rouge", :population => 7518, :region => region)
    locality = Locality.create(:name => "Port-Cartier", :population => 6758, :region => region)
    locality = Locality.create(:name => "Portneuf", :population => 3086, :region => region)
    locality = Locality.create(:name => "Princeville", :population => 5571, :region => region)
    locality = Locality.create(:name => "Prévost", :population => 10132, :region => region)
    locality = Locality.create(:name => "Quebec City", :population => 659545, :region => region)
    locality = Locality.create(:name => "Repentigny", :population => 76237, :region => region)
    locality = Locality.create(:name => "Richelieu", :population => 5208, :region => region)
    locality = Locality.create(:name => "Richmond", :population => 3336, :region => region)
    locality = Locality.create(:name => "Rimouski", :population => 42240, :region => region)
    locality = Locality.create(:name => "Rivière-du-Loup", :population => 18586, :region => region)
    locality = Locality.create(:name => "Rivière-Rouge", :population => 4152, :region => region)
    locality = Locality.create(:name => "Roberval", :population => 10544, :region => region)
    locality = Locality.create(:name => "Rosemère", :population => 14173, :region => region)
    locality = Locality.create(:name => "Rouyn-Noranda", :population => 39924, :region => region)
    locality = Locality.create(:name => "Saguenay", :population => 143692, :region => region)
    locality = Locality.create(:name => "Sainte-Adèle", :population => 10634, :region => region)
    locality = Locality.create(:name => "Sainte-Agathe-des-Monts", :population => 9679, :region => region)
    locality = Locality.create(:name => "Sainte-Anne-de-Beaupré", :population => 2803, :region => region)
    locality = Locality.create(:name => "Sainte-Anne-de-Bellevue", :population => 5197, :region => region)
    locality = Locality.create(:name => "Sainte-Anne-des-Monts", :population => 6772, :region => region)
    locality = Locality.create(:name => "Sainte-Anne-des-Plaines", :population => 13001, :region => region)
    locality = Locality.create(:name => "Saint-Augustin-de-Desmaures", :population => 17281, :region => region)
    locality = Locality.create(:name => "Saint-Basile", :population => 2560, :region => region)
    locality = Locality.create(:name => "Saint-Basile-le-Grand", :population => 15605, :region => region)
    locality = Locality.create(:name => "Saint-Bruno-de-Montarville", :population => 24388, :region => region)
    locality = Locality.create(:name => "Sainte-Catherine", :population => 16211, :region => region)
    locality = Locality.create(:name => "Sainte-Catherine-de-la-Jacques-Cartier", :population => 5021, :region => region)
    locality = Locality.create(:name => "Saint-Césaire", :population => 5151, :region => region)
    locality = Locality.create(:name => "Saint-Colomban", :population => 13080, :region => region)
    locality = Locality.create(:name => "Saint-Constant", :population => 23957, :region => region)
    locality = Locality.create(:name => "Saint-Eustache", :population => 42062, :region => region)
    locality = Locality.create(:name => "Saint-Félicien", :population => 10477, :region => region)
    locality = Locality.create(:name => "Saint-Gabriel", :population => 2828, :region => region)
    locality = Locality.create(:name => "Saint-Georges", :population => 30113, :region => region)
    locality = Locality.create(:name => "Saint-Hyacinthe", :population => 55823, :region => region)
    locality = Locality.create(:name => "Saint-Jean-sur-Richelieu", :population => 87492, :region => region)
    locality = Locality.create(:name => "Saint-Jérôme", :population => 63729, :region => region)
    locality = Locality.create(:name => "Saint-Joseph-de-Beauce", :population => 4454, :region => region)
    locality = Locality.create(:name => "Saint-Joseph-de-Sorel", :population => 1686, :region => region)
    locality = Locality.create(:name => "Sainte-Julie", :population => 29019, :region => region)
    locality = Locality.create(:name => "Saint-Lambert", :population => 21599, :region => region)
    locality = Locality.create(:name => "Saint-Lazare", :population => 17016, :region => region)
    locality = Locality.create(:name => "Saint-Lin–Laurentides", :population => 14159, :region => region)
    locality = Locality.create(:name => "Saint-Marc-des-Carrières", :population => 2774, :region => region)
    locality = Locality.create(:name => "Sainte-Marguerite-du-Lac-Masson", :population => 2498, :region => region)
    locality = Locality.create(:name => "Sainte-Marie", :population => 11584, :region => region)
    locality = Locality.create(:name => "Sainte-Marthe-sur-le-Lac", :population => 11311, :region => region)
    locality = Locality.create(:name => "Saint-Ours", :population => 1700, :region => region)
    locality = Locality.create(:name => "Saint-Pamphile", :population => 2704, :region => region)
    locality = Locality.create(:name => "Saint-Pascal", :population => 3504, :region => region)
    locality = Locality.create(:name => "Saint-Pie", :population => 5109, :region => region)
    locality = Locality.create(:name => "Saint-Raymond", :population => 9273, :region => region)
    locality = Locality.create(:name => "Saint-Rémi", :population => 6136, :region => region)
    locality = Locality.create(:name => "Saint-Sauveur", :population => 9191, :region => region)
    locality = Locality.create(:name => "Sainte-Thérèse", :population => 25224, :region => region)
    locality = Locality.create(:name => "Saint-Tite", :population => 3826, :region => region)
    locality = Locality.create(:name => "Salaberry-de-Valleyfield", :population => 39672, :region => region)
    locality = Locality.create(:name => "Schefferville", :population => 202, :region => region)
    locality = Locality.create(:name => "Scotstown", :population => 588, :region => region)
    locality = Locality.create(:name => "Senneterre", :population => 2993, :region => region)
    locality = Locality.create(:name => "Sept-Îles", :population => 27827, :region => region)
    locality = Locality.create(:name => "Shawinigan", :population => 51904, :region => region)
    locality = Locality.create(:name => "Sherbrooke", :population => 186952, :region => region)
    locality = Locality.create(:name => "Sorel-Tracy", :population => 34076, :region => region)
    locality = Locality.create(:name => "Stanstead", :population => 2957, :region => region)
    locality = Locality.create(:name => "Sutton", :population => 3805, :region => region)
    locality = Locality.create(:name => "Témiscaming", :population => 2697, :region => region)
    locality = Locality.create(:name => "Témiscouata-sur-le-Lac", :population => , :region => region)
    locality = Locality.create(:name => "Terrebonne", :population => 94703, :region => region)
    locality = Locality.create(:name => "Thetford Mines", :population => 25704, :region => region)
    locality = Locality.create(:name => "Thurso", :population => 2299, :region => region)
    locality = Locality.create(:name => "Trois-Pistoles", :population => 3500, :region => region)
    locality = Locality.create(:name => "Trois-Rivières", :population => 129100, :region => region)
    locality = Locality.create(:name => "Val-d'Or", :population => 31123, :region => region)
    locality = Locality.create(:name => "Valcourt", :population => 2349, :region => region)
    locality = Locality.create(:name => "Varennes", :population => 20950, :region => region)
    locality = Locality.create(:name => "Vaudreuil-Dorion", :population => 25789, :region => region)
    locality = Locality.create(:name => "Victoriaville", :population => 40486, :region => region)
    locality = Locality.create(:name => "Ville-Marie", :population => 2696, :region => region)
    locality = Locality.create(:name => "Warwick", :population => 4804, :region => region)
    locality = Locality.create(:name => "Waterloo", :population => 4054, :region => region)
    locality = Locality.create(:name => "Waterville", :population => 1926, :region => region)
    locality = Locality.create(:name => "Westmount", :population => 20494, :region => region)
    locality = Locality.create(:name => "Windsor", :population => 5239, :region => region)